{"id":85954,"title":"20 | panic和recover","content":"<h1>课件及源代码地址</h1><p><a href=\"https://gitee.com/geektime-geekbang/go_learning\">https://gitee.com/geektime-geekbang/go_learning</a></p><h2>书目推荐</h2><p><a href=\"time://mall?url=https%3A%2F%2Fh5.youzan.com%2Fv2%2Fgoods%2F1ycmk3uob0ryw\">《计算机程序的构造和解释》</a></p>","comments":[{"had_liked":false,"id":158892,"user_name":"王先森","can_delete":false,"product_type":"c3","uid":1022267,"ip_address":"","ucode":"1AF1A395107479","user_header":"https://static001.geekbang.org/account/avatar/00/0f/99/3b/791d0f5e.jpg","comment_is_top":false,"comment_ctime":1575471516,"is_pvip":false,"replies":[{"id":61475,"content":"func TestPanicVxExit(t *testing.T) {\n\n\tdefer func() {\n\t\tif err := recover(); err != nil {\n\t\t\tfmt.Println(&quot;recovered from &quot;, err)\n\t\t}\n\t}()\n\tfmt.Println(&quot;Start&quot;)\n\tpanic(errors.New(&quot;Something wrong!&quot;))\n}\n\n&#47;&#47;output:\nStart\nrecovered from  Something wrong!\n\n从输出你可以看出defer处理了panic中抛出的error","user_name":"作者回复","user_name_real":"ChaoCai2010","uid":1008262,"ctime":1576159576,"ip_address":"","comment_id":158892,"utype":1}],"discussion_count":3,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"老师的视频中 第一个例子貌似defer的执行结果看。是在panic之前，费解？","like_count":5,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":476884,"discussion_content":"func TestPanicVxExit(t *testing.T) {\n\n\tdefer func() {\n\t\tif err := recover(); err != nil {\n\t\t\tfmt.Println(&amp;quot;recovered from &amp;quot;, err)\n\t\t}\n\t}()\n\tfmt.Println(&amp;quot;Start&amp;quot;)\n\tpanic(errors.New(&amp;quot;Something wrong!&amp;quot;))\n}\n\n//output:\nStart\nrecovered from  Something wrong!\n\n从输出你可以看出defer处理了panic中抛出的error","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1576159576,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2}","child_discussion_number":0,"child_discussions":[]},{"author":{"id":2890901,"avatar":"https://static001.geekbang.org/account/avatar/00/2c/1c/95/3d8920c9.jpg","nickname":"abcdabcd999","note":"","ucode":"E1D9902737F544","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":600321,"discussion_content":"肯定是在 panic 之后啊，你 defer 函数的输出都拿到Something wrong 了，你说是谁先执行的，绝了这问题","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1674207438,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"山西","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]},{"author":{"id":1350159,"avatar":"https://static001.geekbang.org/account/avatar/00/14/9a/0f/da7ed75a.jpg","nickname":"芒果少侠","note":"","ucode":"98D0BBB52BB80F","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":403662,"discussion_content":"单纯从输出来看，似乎确实是先defer再panic了。但通过老师这个答案可以看到，在defer函数里，已经能捕获到panic的error了，说明是先panic的。只是输出顺序问题","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1634127844,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":280842,"user_name":"申","can_delete":false,"product_type":"c3","uid":2033634,"ip_address":"","ucode":"CE7BFCF552B4F1","user_header":"https://static001.geekbang.org/account/avatar/00/1f/07/e2/32c9a634.jpg","comment_is_top":false,"comment_ctime":1614418032,"is_pvip":false,"replies":[{"id":102102,"content":"😊","user_name":"作者回复","user_name_real":"蔡超","uid":1008262,"ctime":1614647534,"ip_address":"","comment_id":280842,"utype":1}],"discussion_count":1,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"panic能够改变程序的控制流，调用 panic 后会立刻停止执行当前函数的剩余代码，并在当前 Goroutine 中递归执行调用方的defer；\nrecover可以中止 panic 造成的程序崩溃。它是一个只能在 defer 中发挥作用的函数，在其他作用域中调用不会发挥作用。","like_count":4,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":516225,"discussion_content":"😊","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1614647534,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2}","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":82838,"user_name":"行军伙夫","can_delete":false,"product_type":"c3","uid":1198350,"ip_address":"","ucode":"DC1792FDBC8D38","user_header":"https://static001.geekbang.org/account/avatar/00/12/49/0e/6121d428.jpg","comment_is_top":false,"comment_ctime":1554338299,"is_pvip":false,"replies":[{"id":29962,"content":"你是什么操作系统？试试echo $?","user_name":"作者回复","user_name_real":"ChaoCai2010","uid":1008262,"ctime":1554364449,"ip_address":"","comment_id":82838,"utype":1}],"discussion_count":6,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"老师，为啥我os.Exit(-1)，在输出的地方没有看到exit status 255","like_count":4,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":445746,"discussion_content":"你是什么操作系统？试试echo $?","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1554364449,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2}","child_discussion_number":0,"child_discussions":[]},{"author":{"id":1356077,"avatar":"https://static001.geekbang.org/account/avatar/00/14/b1/2d/661132f3.jpg","nickname":"佚名","note":"","ucode":"A4E35B21AC3C31","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":102612,"discussion_content":"mac os mojave 10.14.6没有这行，echo $?结果是0","likes_number":1,"is_delete":false,"is_hidden":false,"ctime":1577356865,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]},{"author":{"id":1435172,"avatar":"https://static001.geekbang.org/account/avatar/00/15/e6/24/30806a88.jpg","nickname":"right-chen","note":"","ucode":"E0E940E80E7A2D","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":582687,"discussion_content":"mac os ，同样这样的情况","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1659597026,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"北京","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]},{"author":{"id":1077127,"avatar":"https://static001.geekbang.org/account/avatar/00/10/6f/87/669263b4.jpg","nickname":"陈金鑫","note":"","ucode":"609A24832CA80C","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":397867,"discussion_content":"Ubuntu系统是：exit status 255","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1632686707,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]},{"author":{"id":1899341,"avatar":"https://static001.geekbang.org/account/avatar/00/1c/fb/4d/c5ac9df5.jpg","nickname":"Vicky~婵娟","note":"","ucode":"E10E28773B60F9","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":216256,"discussion_content":"我的也是没看到任何信息","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1585410930,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]},{"author":{"id":1442588,"avatar":"https://static001.geekbang.org/account/avatar/00/16/03/1c/c9fe6738.jpg","nickname":"Kvicii.Y","note":"","ucode":"446BFA633569EA","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":172460,"discussion_content":"俺也一样","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1581778457,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":135688,"user_name":"iMARS","can_delete":false,"product_type":"c3","uid":1113733,"ip_address":"","ucode":"10C5C31908AA09","user_header":"https://static001.geekbang.org/account/avatar/00/10/fe/85/9ab352a7.jpg","comment_is_top":false,"comment_ctime":1569241648,"is_pvip":false,"replies":[{"id":52938,"content":"go不是采用异常机制的，而是采用错误机制\nfun m3() error{\n    ...\n    return errors.New(&quot;failed to run m3&quot;)\n}\n\nfunc m2() error{\n     err:=m3()\n     if err!=nil{\n         return err\n     }\n     ...\n}\n\n而panic和recovery也并不是如其他语言的exception那样使用的。\n","user_name":"作者回复","user_name_real":"ChaoCai2010","uid":1008262,"ctime":1569836093,"ip_address":"","comment_id":135688,"utype":1}],"discussion_count":2,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"如何返回调用栈的内部异常？例如，m1 call m2，m2又call了m3，结果m3引发了异常，导致m2失败，如何包裹m3的异常输出？有没有好的pattern或建议？谢谢","like_count":2,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":468304,"discussion_content":"go不是采用异常机制的，而是采用错误机制\nfun m3() error{\n    ...\n    return errors.New(&amp;quot;failed to run m3&amp;quot;)\n}\n\nfunc m2() error{\n     err:=m3()\n     if err!=nil{\n         return err\n     }\n     ...\n}\n\n而panic和recovery也并不是如其他语言的exception那样使用的。\n","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1569836093,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2}","child_discussion_number":0,"child_discussions":[]},{"author":{"id":1352152,"avatar":"http://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaELcM4karUTtLlszX1FPaYKcbsfsthZiahTpYlnFgQIS3PcJStvKTCE9OqbJfgxxzfrg1t0CpuspHCQ/132","nickname":"will","note":"","ucode":"57980692086041","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":42593,"discussion_content":"go1.13新的错误处理wrap方式，现在能满足这个需求。","likes_number":1,"is_delete":false,"is_hidden":false,"ctime":1572705600,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":113611,"user_name":"唯一","can_delete":false,"product_type":"c3","uid":1475143,"ip_address":"","ucode":"6858AB45082E85","user_header":"https://static001.geekbang.org/account/avatar/00/16/82/47/f4430522.jpg","comment_is_top":false,"comment_ctime":1563094245,"is_pvip":false,"replies":[{"id":41827,"content":"recover一般适用于应用程序全局的未处理错误而不是某个函数。\n","user_name":"作者回复","user_name_real":"ChaoCai2010","uid":1008262,"ctime":1563353539,"ip_address":"","comment_id":113611,"utype":1}],"discussion_count":1,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"老师，请问，如果一个函数发生了不可预知的运行时错误，我们怎么让这个函数返回一个自定义的值，我在defer的函数里调用了recover后，发现函数返回的是返回数据类型的零值，但有没有办法自定义这个运行时错误的返回值？","like_count":2,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":458308,"discussion_content":"recover一般适用于应用程序全局的未处理错误而不是某个函数。\n","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1563353539,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2}","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":389121,"user_name":"王广大","can_delete":false,"product_type":"c3","uid":1645005,"ip_address":"浙江","ucode":"4FC4732B13CFB6","user_header":"https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJgdor14prMkNrYCn0bxKF4tVB86DO5peVBxpOsicMHhNPF8COlcWfoKdpJsRibfKQ7l7Ou8zSeJzrA/132","comment_is_top":false,"comment_ctime":1711616827,"is_pvip":false,"replies":[{"id":141636,"content":"panic 退出前会执⾏ defer 指定的内容","user_name":"作者回复","user_name_real":"编辑","uid":1008262,"ctime":1712110624,"ip_address":"北京","comment_id":389121,"utype":1}],"discussion_count":1,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"func TestPanicVxExit(t *testing.T) {\n\n\tdefer func() {\n\n\t\tfmt.Println(&quot;testing...........&quot;)\n\t\t&#47;&#47;if err := recover(); err != nil {\n\t\t&#47;&#47;\tfmt.Println(&quot;recovered from&quot;, err)\n\t\t&#47;&#47;}\n\t}()\n\tfmt.Println(&quot;Start&quot;)\n\tpanic(errors.New(&quot;Something wrong&quot;))\n\tfmt.Println(&quot;End&quot;)\n\n}\n\n执行结果\n=== RUN   TestPanicVxExit\nStart\ntesting...........\n--- FAIL: TestPanicVxExit (0.00s)\npanic: Something wrong [recovered]\n\tpanic: Something wrong\n\n从执行结果看貌似是defer 先于panic 执行的","like_count":0,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":641037,"discussion_content":"panic 退出前会执⾏ defer 指定的内容","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1712110624,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"北京","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2,\"source\":0}","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":332858,"user_name":"slssdhs","can_delete":false,"product_type":"c3","uid":1138058,"ip_address":"","ucode":"6644520A415C69","user_header":"https://static001.geekbang.org/account/avatar/00/11/5d/8a/894479c1.jpg","comment_is_top":false,"comment_ctime":1643743855,"is_pvip":false,"replies":[{"id":127021,"content":"返回的是panic的错误信息，在调用panic时可以传入错误信息。例如：panic(“something is wrong”)","user_name":"作者回复","user_name_real":"编辑","uid":1008262,"ctime":1655601747,"ip_address":"","comment_id":332858,"utype":1}],"discussion_count":1,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"您好 请问一下为什么从panic恢复的代码是那么写的？更具体来说是 if err := recover(); err != nil 这里. 此处err被赋值了一个函数，为什么还是能接收到错误信息呢？还是说我理解错了？","like_count":0,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":576492,"discussion_content":"返回的是panic的错误信息，在调用panic时可以传入错误信息。例如：panic(“something is wrong”)","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1655601747,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2}","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":286742,"user_name":"escray","can_delete":false,"product_type":"c3","uid":1020525,"ip_address":"","ucode":"1F4204930E47C4","user_header":"https://static001.geekbang.org/account/avatar/00/0f/92/6d/becd841a.jpg","comment_is_top":false,"comment_ctime":1617544671,"is_pvip":true,"replies":[{"id":104463,"content":"使用代main的go程序，让后编译。执行编译后的二进制。在通过echo $?","user_name":"作者回复","user_name_real":"蔡超","uid":1008262,"ctime":1618104880,"ip_address":"","comment_id":286742,"utype":1}],"discussion_count":2,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"恢复机制常常被错误使用，只是简单的打印的错误信息，或者是吞噬了异常。\n\n在 Go 语言里面，一般说是错误处理，而不是异常处理。\n\n我的 os.Exit(-1) 也没有输出错误代码 255，echo $? 的结果是：0\n\nmacOS Big Sur 11.2.3\n\nfunc TestPanicVsExit(t *testing.T) {\n\tdefer func() {\n\t\tfmt.Println(&quot;Finally&quot;)\n\t}()\n\tdefer func() {\n\t\tif err := recover(); err != nil {\n\t\t\tfmt.Println(&quot;recovered from &quot;, err)\n\t\t}\n\t}()\n\tfmt.Println(&quot;Start&quot;)\n\tpanic(errors.New(&quot;something wrong!&quot;))\n\t&#47;&#47; os.Exit(-1)\n\t&#47;&#47; fmt.Println(&quot;End&quot;)\n}","like_count":0,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":518078,"discussion_content":"使用代main的go程序，让后编译。执行编译后的二进制。在通过echo $?","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1618104880,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2}","child_discussion_number":0,"child_discussions":[]},{"author":{"id":2890901,"avatar":"https://static001.geekbang.org/account/avatar/00/2c/1c/95/3d8920c9.jpg","nickname":"abcdabcd999","note":"","ucode":"E1D9902737F544","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":600322,"discussion_content":"n 次踩坑告诉我 不要使用 macos 作为你的开发系统，它只是用来写文档的，开发环境还是要用 ubuntu","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1674207830,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"山西","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":146928,"user_name":"will","can_delete":false,"product_type":"c3","uid":1352152,"ip_address":"","ucode":"57980692086041","user_header":"http://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaELcM4karUTtLlszX1FPaYKcbsfsthZiahTpYlnFgQIS3PcJStvKTCE9OqbJfgxxzfrg1t0CpuspHCQ/132","comment_is_top":false,"comment_ctime":1572705255,"is_pvip":false,"replies":[{"id":56771,"content":"defer定义的范围对吗？粘贴一下你的代码吧","user_name":"作者回复","user_name_real":"ChaoCai2010","uid":1008262,"ctime":1572744991,"ip_address":"","comment_id":146928,"utype":1}],"discussion_count":1,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"老师，请问，我的defer函数里面再调用一个函数使用了recover，为什么catch不了panic？","like_count":0,"discussions":[{"author":{"id":1008262,"avatar":"https://static001.geekbang.org/account/avatar/00/0f/62/86/632ad029.jpg","nickname":"蔡超","note":"","ucode":"4C281BBF511238","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":473060,"discussion_content":"defer定义的范围对吗？粘贴一下你的代码吧","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1572744991,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2}","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":341550,"user_name":"熊出没","can_delete":false,"product_type":"c3","uid":1145377,"ip_address":"","ucode":"6E39230CC87808","user_header":"https://static001.geekbang.org/account/avatar/00/11/7a/21/a33cc944.jpg","comment_is_top":false,"comment_ctime":1649687593,"is_pvip":false,"replies":null,"discussion_count":0,"race_medal":0,"score":2,"product_id":100024001,"comment_content":"Windows系统 os.Exit(-1)打印的是4294967295","like_count":0},{"had_liked":false,"id":287968,"user_name":"王宝金","can_delete":false,"product_type":"c3","uid":1965760,"ip_address":"","ucode":"D80B4B2CC1C43F","user_header":"https://static001.geekbang.org/account/avatar/00/1d/fe/c0/9c0b3847.jpg","comment_is_top":false,"comment_ctime":1618235967,"is_pvip":false,"replies":null,"discussion_count":1,"race_medal":0,"score":3,"product_id":100024001,"comment_content":"let it  crash是什么意思？老师","like_count":0,"discussions":[{"author":{"id":1622022,"avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJia6zEsh2u119zJicmq7wApvnricZEKiawaZicice1cOzujWdFicFwPtavlHiaVpCNgCpxBtdl7ynd3y0wkQ/132","nickname":"james_xu","note":"","ucode":"12E50291F5BA89","race_medal":0,"user_type":1,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":391851,"discussion_content":"就是不捕获异常，让异常抛出，进程退出","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1630657978,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":false,"parent_id":0,"ip_address":"","group_id":0},"score":2,"extra":"","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":251063,"user_name":"Geek_427d0c","can_delete":false,"product_type":"c3","uid":1876823,"ip_address":"","ucode":"D7A04138C4B8CB","user_header":"https://thirdwx.qlogo.cn/mmopen/vi_32/X4ib36ADEvj76XaKD4OUY9k15KqWCAVCwibPicBxz6BBUfDrVolpYInn8zFOw3JBPtVw3L4Lkibaf2eLPemwGKzAXA/132","comment_is_top":false,"comment_ctime":1601348742,"is_pvip":false,"replies":null,"discussion_count":0,"race_medal":0,"score":3,"product_id":100024001,"comment_content":"哈哈哈哈，“我们先不去说这是不是一个好的习惯”，求生欲非常强了。","like_count":0}]}